
spring:
  application:
    name: spring-book-service
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
      database-platform: org.hibernate.dialect.MySQL55Dialect
    show-sql: true
  datasource:
    url:
springdoc:
  swagger-ui:
    path: /swagger-ui.html
